import type { TransactionRequest } from '../types/api.types';

export const exampleTransactions: Record<string, Partial<TransactionRequest>> = {
  insufficient_funds: {
    transactionId: 'txn_demo_001',
    merchantId: 'mch_demo_123',
    amount: 50000,
    currency: 'COP',
    failureType: 'insufficient_funds',
    failureCode: 'P001',
    failureReason: 'Card has insufficient funds',
    paymentProcessor: 'stripe',
    cardLastFour: '4242',
    attemptNumber: 1,
  },
  network_timeout: {
    transactionId: 'txn_demo_002',
    merchantId: 'mch_demo_456',
    amount: 30000,
    currency: 'COP',
    failureType: 'network_timeout',
    failureCode: 'N001',
    failureReason: 'Network timeout occurred',
    paymentProcessor: 'nequi',
    cardLastFour: '5555',
    attemptNumber: 1,
  },
  card_stolen: {
    transactionId: 'txn_demo_003',
    merchantId: 'mch_demo_789',
    amount: 75000,
    currency: 'COP',
    failureType: 'card_stolen',
    failureCode: 'F001',
    failureReason: 'Card reported as stolen',
    paymentProcessor: 'pse',
    cardLastFour: '1234',
    attemptNumber: 1,
  },
  rate_limit: {
    transactionId: 'txn_demo_004',
    merchantId: 'mch_demo_999',
    amount: 40000,
    currency: 'COP',
    failureType: 'card_declined',
    failureCode: 'P002',
    failureReason: 'Card was declined',
    paymentProcessor: 'stripe',
    cardLastFour: '9999',
    attemptNumber: 5,
  },
  small_amount: {
    transactionId: 'txn_demo_005',
    merchantId: 'mch_demo_555',
    amount: 5000,
    currency: 'COP',
    failureType: 'insufficient_funds',
    failureCode: 'P001',
    failureReason: 'Card has insufficient funds',
    paymentProcessor: 'stripe',
    cardLastFour: '8888',
    attemptNumber: 1,
  },
  processor_downtime: {
    transactionId: 'txn_demo_006',
    merchantId: 'mch_demo_101',
    amount: 45000,
    currency: 'COP',
    failureType: 'processor_downtime',
    failureCode: 'P003',
    failureReason: 'Payment processor is down',
    paymentProcessor: 'stripe',
    cardLastFour: '7777',
    attemptNumber: 1,
  },
};
